exclude:
  - readme.md
  - .github/
header_pages:
  - index.md
author: ib
twitter_username: CegosIb
github_username:  renaudwangler
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
theme: jekyll-theme-slate
defaults:
  -
    scope:
      path: "stages"
    values:
      layout: "stage"
title: "ib - apts"
url: ib-apts